# Generated by Django 6.1 on 2026-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=300)),
                ('writer_email', models.CharField(max_length=500)),
                ('writer_message', models.TextField()),
            ],
        ),
    ]
