# Generated by Django 6.1 on 2026-08-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='اسم آهنگ')),
                ('singer', models.CharField(max_length=200, verbose_name='خواننده ی آهنگ')),
                ('song', models.FileField(upload_to='song', verbose_name='فایل آهنگ')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': 'آهنگ ها',
            },
        ),
    ]
