# Generated by Django 6.0.6 on 2026-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'آهنگ', 'verbose_name_plural': 'آهنگ ها'},
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=400, verbose_name='اسم آهنگ'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=200, verbose_name='خواننده ی آهنگ'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='song', verbose_name='فایل آهنگ'),
        ),
    ]
